### ISSUE TITLE
Adjustable right-alignment of results

### ISSUE THREAD

**Issue by AmadeusW** [CodeConnect/AliveFeedback#109]
Our customer would like to adjust the position of the results.

Initially the results were aligned to the right edge of the screen. However, on very large screens they were too far away from the code which harmed readability. We pulled the results closer towards the code but now they seem to be too close:
![img](https://i.gyazo.com/8e2d5c57476d85ac10af1ce66c210251.png)

There is no one-size-fits-all scenario and we plan on letting the user adjust the margin.

**Comment by AmadeusW** [comment]
work in progress
![](https://i.gyazo.com/72534fd1b410a7a1576b9d5839719c00.gif)

**Comment by AmadeusW** [comment]
This has been fixed in [v1.4.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.4.1)

**Comment by savehansson** [comment]
During my work the editor window varies in width. Sometimes I have Solution Explorer pinned to the left, sometimes it's hidden. As the position of Alive results seems to be measured from the left, it means that the position sometimes is at the right edge, sometimes more to the "middle" of the editor frame (not desirable, for me).

Letting users adjust the margin is great, but now you've moved the problem to "What does the user mean by her/his adjustment? Should it be measured from the left or the right".

You can't know, but since the results are targeting the right side of the code I think it would be better if it was measured from that edge.

**Comment by AmadeusW** [comment]
If you set the margin to be further than the width of the editor, Alive results will be attached to the right edge of the editor. Would this work for you?

The results were initially fixed to 1000px away from the left edge, or at the right edge (whichever distance was smaller), and now you can adjust the 1000px.

I doubt if we will support placement _x pixels away_ from the right edge. Our goal is to accommodate code with both wide and narrow line length on both wide and narrow screens. We saw that placing results _x pixels away_ from the right edge is not a significant use case, but we are willing to revisit this by popular demand.

**Comment by savehansson** [comment]
That is absolutely fine!
