### ISSUE TITLE
Monthly subscription for Alive

### ISSUE THREAD

**Issue by SachiraChin** [CodeConnect/AliveFeedback#111]
I'm not sure this is the right place to ask this but I couldn't find anywhere else to put it, it'd be great if you have monthly subscription for the extension. You can be price it for $9.99 to be fair. I'm saying it because I'm more comfortable with paying monthly rather than annually for subscription and I'm sure there are people who like to use your extension and can pay only for a monthly subscription like this. 

Please consider if you can. Thanks!

**Comment by JoshVarty** [comment]
Hi @SachiraChin. When we first priced Alive we considered a monthly subscription after which Alive stopped working. However the majority of developers [were very upset](http://bytecrafter.blogspot.ca/2015/09/how-jetbrains-lost-years-of-customer.html) when JetBrains proposed they were moving to a similar model. 

In order to keep things simple and avoid confusion we'd like to have just one pricing model. With that being said, we'll definitely act on this feedback if we start to hear it echoed by more users.

I'll close this for now, but feel free to let me know if you have any questions about pricing.

**Comment by SachiraChin** [comment]
I do believe you put your best thoughts to this and I hope one day you will have monthly subscription. I'm using JetBrains monthly full version and I only able to purchase after they relesed that version. I'm not asking you to stop annual subscription but to add monthly as well. Hope best for you all. Thanks.

Get Outlook

On Thu, Apr 7, 2016 at 12:24 PM -0700, "Josh Varty" notifications@github.com wrote:

Hi @SachiraChin. When we first priced Alive we considered a monthly subscription after which Alive stopped working. However the majority of developers [were very upset](http://bytecrafter.blogspot.ca/2015/09/how-jetbrains-lost-years-of-customer.html) when JetBrains proposed they were moving to a similar model.

In order to keep things simple and avoid confusion we'd like to have just one pricing model. With that being said, we'll definitely act on this feedback if we start to hear it echoed by more users.

I'll close this for now, but feel free to let me know if you have any questions about pricing.

---
