### ISSUE TITLE
Can I still purchase Alive?

### ISSUE THREAD

**Issue by SCKelemen** [CodeConnect/AliveFeedback#124]
I can't seem to find it anywhere, anymore? When will it be available again?

**Comment by AmadeusW** [comment]
Hi @SCKelemen, thank you for the interest. I’m afraid the extension isn’t available at this time. We plan for Alive to become an integrated feature of a future version of Visual Studio.

**Comment by Rhywden** [comment]
@AmadeusW Which raises the question: If it will become integrated which versions would that require?

Because the "advanced" testing tools like Smart Unit Tests / IntelliTest and UI Tests are only available in 2015 Enterprise. And I frankly don't have the $6,000 it would require to buy a license (or the $3,000/y for the subscription type).

**Comment by AmadeusW** [comment]
Our current plan is that Alive will become a feature in VS "15". We are still in the process of integrating, and we will share concrete plans as they become available to us. I'll update this thread, and you can check out http://aka.ms/vsblog

**Comment by SCKelemen** [comment]
Will it be opensource-ish? Can I add features to it as well, or will it be accessible from VSIX packages, so I can extended it?

**Comment by AmadeusW** [comment]
I don't know the answer to this question, but we will continue to seek and act on feedback from our users! This applies to both feature requests and bug reports. We would like to hear about your use case so that we can either implement it or enable it.

**Comment by proegssilb** [comment]
Looks like Visual Studio 2017 has been released, and looking through the release notes doesn't show any hint of Alive being integrated. Delays happen, but is someone still working on this, or is Alive dead tech?

**Comment by AmadeusW** [comment]
Yes, we're working on it. I hope that we'll be able to share more information within a few weeks.

**Comment by Kazpers** [comment]
Hope for some good news. Just discovered this extension today (through your Roslyn TV clips), and was extremely sad to find it was not available anymore. Haven't seen any hint of "Alive" in VS 17 either, although I'm following the release pretty closely so I'm worried. Hope for the best.

**Comment by Rhywden** [comment]
And, again, I do hope that it's not something that will be only available for the Enterprise editions (as is the case for various other Testing methods). Currently I'm doing fine with the Community Edition and I could afford the Professional one but Enterprise would not make any sense for me, fiscally-wise.

**Comment by UlyssesWu** [comment]
It has been 8 weeks and I really miss Alive... Without Alive and PTVS, VS2017 is just incomplete.

**Comment by AxisRay** [comment]
Add 4 weeks……

**Comment by SCKelemen** [comment]
"Yes, we're working on it. I hope that we'll be able to share more information _**within a few weeks**_."
- @AmadeusW , 07 March 2017

**Comment by SCKelemen** [comment]
@JoshVarty Any chance this will ever be available again?

**Comment by UlyssesWu** [comment]
Sadly, after upgraded VS2017 to Update3, we still don't have Alive inside.
So I decided to _port_ it by myself... and I succeed. In fact, I think maybe just removing one single hard code VS version check is enough to do the trick. But I actually spent about 2 days on it, most time on fixing references. The point is - there are almost no compatibility issues for Alive to run on VS2017.

I called it **ReLive** :
![relivedemo](https://user-images.githubusercontent.com/4312781/29420894-f65a3972-83a5-11e7-9998-c511b9da8779.png)

It has no new features, no support for .NET Core, and sometimes even throw exceptions... but at least it works. 😝 I don't think I can/will provide the file to anyone, but I do hope Alive could be a free feature for all versions of VisualStudio...

*The name "ReLive" comes from an anime called "ReLIFE".

**Comment by SCKelemen** [comment]
@UlyssesWu do I need an alive license for it?

**Comment by AxisRay** [comment]
@SCKelemen 
No.
In fact, he won't provide it for anyone unless the author abandoned copyright.

He just proved that the author was too "LAZY".😝
The license is not cheap, after all.

:)

**Comment by AxisRay** [comment]
@AmadeusW
If you are so busy at that time that have no time to maintain the project.
Would you like to consider opening source it?
Just a suggestion

**Comment by SCKelemen** [comment]
@AmadeusW @JoshVarty Are the any hopes for us? Have you forsaken us?

**Comment by JoshVarty** [comment]
**Short version:** As far as I know, Alive won't be shipped for Visual Studio 2017.

**Long Version:** When we joined Microsoft we did so with the intent of shipping Alive alongside Visual Studio 2017. Unfortunately, visa problems and other issues delayed our start date by over two months. When we finally started in September 2017, we sat down and estimated the work necessary to get Alive up to Visual Studio standards. We looked at performance, stability and overall quality. 

After presenting our estimates, it was decided that we should not rush things, and we should instead wait until after Visual Studio shipped to evaluate how Alive might fit into Visual Studio.

From December 2016 to March 2017 we ran a number of private experiments with hundreds of users of Visual Studio. The goal of these experiments was to identify problems our customers were having and understand if Alive was the best way to solve these problems.

Ultimately, it was decided that Alive was not solving huge problems that our customers were facing, or at least that there were other technologies in which we could invest that might help more customers.

(Disclaimer: I should also note that I've recently left Microsoft.)

I'm genuinely sorry that it had to come to this. We had big dreams for Alive including bringing it to other languages and platforms. 

I'm also sorry for keeping everyone in the dark for so long. That wasn't intentional, Amadeus and myself were also unsure of what Alive's future would be.

I should also note that existing customers of Alive will continue to have access to the Visual Studio 2015 bits. You can request a copy of the `.vsix` from `aliveq@microsoft.com`

**Comment by SCKelemen** [comment]
Thanks for closing the loop. Good luck in the future.

**Comment by proegssilb** [comment]
...and those of us that never had a chance to obtain a copy of Alive will never be able to get it? MS's existing tech, including IntelliTrace, doesn't quite work as nicely...

Thanks for giving us the honest answer.

**Comment by SCKelemen** [comment]
I agree, I'd still like to be able to obtain a copy somehow.

**Comment by AmadeusW** [comment]
I've been humbled by the your perseverance, willingness to contribute to open source project and the fact that @UlyssesWu made ReLive!

Thanks to every single question and message we received from our customers and non-customers, we now have a reasonable shot at open sourcing Alive. I've been engaging multiple people at Microsoft to open source this, and your involvement sways the decision towards open sourcing in a big way. 

So far, a major worry is that since the code would be released under Microsoft's repo, there will be an expectation of certain level of quality - e.g. that a VS update must not break the extension. The management is very conservative since Productivity Power Tools extension always requires a lot of maintenance. I'm confident that Alive won't need maintenance like this, since it never did and we had no issues migrating from VS 2015 to 2017. This is where community comes in play, since the proposed open source repo would be maintained by me on my spare time or by the community as a whole.

I will keep advocating to open source Alive. Thank you for being here, it wouldn't be possible without you!

--- 

P.S.
> "Yes, we're working on it. I hope that we'll be able to share more information within a few weeks."
@AmadeusW , 07 March 2017

I was told that we'll know more in "couple weeks". 
I'm sorry for lack of communication, but I want you to know that Alive is on my mind every day.

**Comment by Kazpers** [comment]
@AmadeusW Any news on this?
