### ISSUE TITLE
Discovery of xUnit 2.x tests

### ISSUE THREAD

**Issue by Mpdreamz** [CodeConnect/AliveFeedback#49]
In our 2.0 branch we moved to xUnit 2.0 and [use custom fact attributes](XunitTestCaseDiscoverer) to selectively run tests depending on wether we run in integration `[I]` or unit test `[U]` mode.

See e.g here: https://github.com/elastic/elasticsearch-net/blob/2.0/src/Tests/ClientConcepts/ConnectionPooling/MaxRetries/RespectsMaxRetry.doc.cs

Sadly Alive does not detect any tests in our solution on this branch.

**Comment by JoshVarty** [comment]
Thanks, I'll pull down the `elasticsearch-net` repo and try to figure this one out.

**Comment by JoshVarty** [comment]
Good news, I've got it working correctly. Now we'll just have to review, but I anticipate we can get this out to you sometime late tomorrow afternoon. 

![image](https://cloud.githubusercontent.com/assets/1249087/10779804/0747c13e-7d0c-11e5-906a-069f62dfc726.png)

**Comment by Mpdreamz** [comment]
Awesome! looking forward to being able to play with Alive! :+1: 

Amazing turn around time :ship:

**Comment by JoshVarty** [comment]
So the issue you've pointed out has been fixed in v1.0.1 which you can get from the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/4af8eb1a-c64f-4da8-9bf0-6835cf3e95c8). (VS 2015 also automatically updates extensions, so it may already have pulled it down for you when you restart).

I ran into a bug with class fixtures and another with asynchronous tests (which I fixed in #50).

There's also an error when auto-filtering (#51) which I should have fixed for tomorrow.

I'll go ahead and close this now that this particular issue is fixed.
