### ISSUE TITLE
Getting some info

### ISSUE THREAD

**Issue by jotaoro** [CodeConnect/AliveFeedback#5]
Hi Guys...

Great tool !!, 

Discussing with the company dev team some questions have arisen about the actual state of Alive and your license terms which ones i hope you can clarify me.
1. Actually exist any version of the tool enabled for purchase?, or be the June 1st Alpha realesed the first one??
2. As we know, the license will be valid per year, but according with the roadmap, between october and november the license will be extended, would be correct if we say "we have +1 year", in other words, we have the license tool valid for 2 years?
3. The license is per dev machine, right?

Thanks for your response.

**Comment by AmadeusW** [comment]
Hi @jotaoro,
1. The first version available publicly will be released on June 1st.
2. If we release Alive 1.0 in October, then your license will be valid until October 2016
3. The license is per developer, you can hack away at your projects at home

Let me know if you have any other questions

**Comment by colombod** [comment]
Sorry, this may be the wrong place. I did purchase a license early today but i still have not received neither billing acknowledgment nor the license.  What can I do?

**Comment by AmadeusW** [comment]
Thank you for pointing this out! We're sorry but the email with the license key has bounced. Perhaps there was a typo? I see you provided email address containing ...colombid...

I'm trying to re-send it to both emails with ...colombid... and ...colombod... 
If you don't see any email from us, please email me at amadeus@codeconnect.io

Furthermore, I've just enabled forwarding of bounce messages to our inbox, so that in the future we will be notified when this happens again.

**Comment by colombod** [comment]
sorry, yes a typo. Got the license last night, now time to have fun with your product!
