### ISSUE TITLE
Cannot view superclass members in Alive preview boxes.

### ISSUE THREAD

**Issue by Ijwu** [CodeConnect/AliveFeedback#67]
I wasn't sure how you prefer issues so I decided to be separate. This issue is quite similar to #66. In this case, it would be logical to view superclass members of objects which derive from classes in non-standard library code.

![Preview Box](http://puu.sh/mp4VY/97022be168.png)

The instance in the preview box shown above definitely has more members. They're simply members defined in the parent class. Viewing them in the preview would be an improvement.

**Comment by AmadeusW** [comment]
It's a matter of providing information vs generating clutter. I'm in for displayin base class properties, perhaps under a gentle visual separator. @JoshVarty what are your thoughts?

**Comment by JoshVarty** [comment]
Showing base class members is definitely something we'd like to support. We can probably squeeze this into next week's release.

I'm not really concerned about clutter because the drilldown menus aren't displayed by default. But we should investigate what the experience is like when the results extend off the screen.

**Comment by AmadeusW** [comment]
This feature will be available in the upcoming update. Thank you @ljwu

**Comment by AmadeusW** [comment]
Fixed in [1.2.1](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.2.1) :tropical_drink:
