### ISSUE TITLE
VS 2013 - no response

### ISSUE THREAD

**Issue by eOkadas** [CodeConnect/AliveFeedback#92]
Hi,

Using Alive with the shortcut or through the button "Launch Alive here", just gets me the status bar message "To start using Alive, navigate to a method first."

I've disabled ncrunch and resharper just in case, restarted VS, clicked all over the place. Still stuck there.

console output:

```
[Message v1.3.8-vs12.0] To start using Alive, navigate to a method first.
```

.NET 4.6 and vs tools 2015 installed.

**Comment by AmadeusW** [comment]
Thank you for reaching out and I'm very sorry that it's not working for you. 
Let me investigate behavior with VS2013 and I'll get back to you.

**Comment by AmadeusW** [comment]
I can't reproduce this issue. Looking at the code responsible for this error message, it appears that the file name provided to Alive from Visual Studio editor does not match the file name associated with the button. 

Can you please help me narrow down the issue? 
- Does this happen in every file? 
- Does this happen in every solution? 
- Is there anything peculiar about the file, such as 
  - being on the network, 
  - not having a `.cs` extension, or 
  - its name has non-standard characters?

In the meanwhile, I will add code that gathers more relevant information for the error report. We will ship this code in the next update (today or within a few days) and hopefully this could also help us deduce what's happening.

**Comment by AmadeusW** [comment]
@eOkadas we've updated Alive yesterday to [v1.3.9](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-1.3.9). In this version we're collecting more data about the issue that you have. Please let us know when you try again and then I'll look at the exception report.

**Comment by eOkadas** [comment]
Hi, 

thanks for looking into it. (I'm also the person who emailed about issues to activate from behind a proxy)

After updating the error now looks like

``` Alive
[Message v1.3.9-vs12.0] To start using Alive, navigate to a method first.
[Error v1.3.9-vs12.0] Error starting Alive. Please navigate to a method and try again.
[Error v1.3.9-vs12.0]  -> Alive button for C:\HOMEWARE\Path\Lama.Domain\SomethingService.cs hasn't been registered.
Parameter name: filePath
```

I get that on methods, unit test methods, anywhere in all the files / projects I tried. I switched to other projects we've got, they all react like the same way so it might my config.

**Comment by AmadeusW** [comment]
@eOkadas I've been trying to figure out what can go wrong and here are a few scenarios that can cause this error:
- The file is "transient" - its editor is active because you clicked on the file in the solution explorer, just like `BaseMethodDeclaration.cs` below: is this how the file is loaded?
  ![img](https://i.gyazo.com/a75de8460fbf26e8eaad559218109f57.png)
- The error indicates that there is no button on the screen. Are you launching Alive by clicking the Alive button?
  ![img](https://i.gyazo.com/db71e48093d09c56dc4113a598a15a8f.png)

Thank you for the leads. This helps narrow down the investigation.

**Comment by AmadeusW** [comment]
I also noticed that together with issues with launching, users (it could be you or another user) might have had issues with Alive handling resources and files auto-generated by Entity Framework. These issues are most likely not a cause of your issue, but they seem to correlate with it and that's why I'm investigating them.

We are also investigating an issue with positioning of the Alive launch button. It might be related but it might be a separate issue, since it looks like your button does not exist at all.

**Comment by eOkadas** [comment]
![image](https://cloud.githubusercontent.com/assets/14233213/13454956/be52dbc8-e05a-11e5-9415-4a04b10f49b5.png)

I only have buttons in view/Other windows, the alive button doesn't show up. I click on 'launch alive here' or try the keyboard shortcut.

And yes it happens on files that are fully opened, pinned and all that.

It's okay if you can't pin the issue down, we'll switch to vs 2015 in 6 months and I'll revisit the idea of testing it.

**Comment by AmadeusW** [comment]
Okay, this narrows the issue down to the fact that the Alive button doesn't show up.
I'm sorry that you didn't get to use Alive and I will keep trying to get it working. When you move to VS2015 or when we fix this issue, I'll extend your trial.

**Comment by AmadeusW** [comment]
Since Alive loads partially on your machine (the menu item registers, but the UI doesn't), there might be a conflict between Alive's DLLs and these that come with Visual Studio. 

By the way, did you install MSBuild Tools 2015 and apply VS 2013 patch? The steps are available at https://comealive.io/Docs/InstallationOnVS2013

If yes, then can you please 
1. Go to the command line and run `"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" /log`, 
2. Click around the editor (which should create the buttons, or in your case, trigger the bug), 
3. Try to launch Alive 
4. Go to `%appdata%\Microsoft\VisualStudio\12.0` and send me an email with `ActivityLog.xml`.

I'm `amadeus@codeconnect.io`
Thank you

**Comment by AmadeusW** [comment]
@eOkadas I ran into a similar issue but it was intermittent. This might be a solution: https://connect.microsoft.com/VisualStudio/feedback/details/1570345/mef-cache-version-mismatch-after-new-install

Please let me know if you'd like to extend your trial!

> Assembly timestamp in MEF Cache does not match loaded assembly timestamp
> 
> For this error, try to run the following two commands:
> 
> Please open Windows Explorer, and navigate to  <Visual Studio Installation Path>\Common7\IDE (by default is C:\Program Files \Microsoft Visual Studio 12.0\Common7\IDE)
> 1. Devenv.exe /UpdateConfiguration
> 2. Devenv.exe /ClearCache

**Comment by AmadeusW** [comment]
Alternatively, you can simply use [Clear MEF Component Cache extension](https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd) by 
Mads Kristensen for the same fix.

**Comment by eOkadas** [comment]
Didn't quite do it. I'll just switch to 2015 eventually.
thanks for trying. Feel free to close the issue, I gave up on installing it with 2013 and won't devote more time to fixing it.

**Comment by AmadeusW** [comment]
Okay, let me know when you do it and I'll re-issue a trial for you.
