### ISSUE TITLE
Start Visual Studio Debugger with alive

### ISSUE THREAD

**Issue by Fosna** [CodeConnect/AliveFeedback#96]
It would be nice if Alive could be started in debugger mode to hit one of my breakpoints it finds along the way.

Does it have such feature already, that I'm not aware of?

**Comment by Fosna** [comment]
Visual Studio already has something similar. 

```
public static class Monkey
{
    public static void Go()
    {
        var name = Path.GetRandomFileName();
        var name2 = string.Join("", name.Reverse()); // put breakpoint here
    }
}
```

In immediate window write `?Monkey.Go()` and press enter. Go method will be executed and debugger will pause on breakpont.

Reference: https://msdn.microsoft.com/en-us/library/83hd8f1e(v=vs.120).aspx

I'm guessing I'd like Alive to "write" `?Monkey.Go()` in immediate window for me. It'd create seamless experience. However there might be some impediments I haven't thought of.

**Comment by AmadeusW** [comment]
Can you tell me more about your end goal? Are you trying to debug another method than the one Alive is running on, and the breakpoint is a convenient way of getting to that method? 
For example, you have Alive running in some other method and you'd like to see what happens in `Go`?

Working with breakpoints and debug session wouldn't be possible because Alive runs separately from the debugger. But let me know what you have in mind, perhaps it would be possible.

**Comment by Fosna** [comment]
Example is to simple. I guess I'd like to see VS debugger level of details for variables in context. Alive hasn't reached that level of details yet. 

Btw. design time debugging in VS 2013 crashes quite often. :(

Anyway, this issue isn't actionable. I'll close it. I'll get back if I have some concrete idea. Thx @AmadeusW .

**Comment by AmadeusW** [comment]
Gotcha. What kind of details are you interested in? 

Did you try clicking on a "+" to the right of Alive results? You can drill down into this object's properties. 
![gif](https://i.gyazo.com/7fbae81eaa75c5a9b45127fd8218a414.gif) 

https://github.com/CodeConnect/AliveFeedback/issues/73 is a request to drill down to deeper levels, kind of like what the debugger does.

**Comment by Fosna** [comment]
I'll give it a try.
